import express from "express";
import { requireAuth, allowRoles } from "../middlewares/authMiddleware.js";
import { approveWorkflowInvoice, attachEvidence, completeChecklist, completePreparation, confirmQuotation, confirmReport, createInvoice, evidenceUpload, generateDraft, getTemplates, getWorkflow, initializeWorkflow, invoiceUpload, listWorkflows, markInspectionComplete, payWorkflowInvoice, rejectWorkflowInvoice, removeEvidence, reviewReport, saveChecklist, savePreparation, selectQuotation, selectTemplate, updateWorkflowStage } from "../controllers/inspectionWorkflowController.js";
import { saveDraft, sendProposal, recallProposal } from "../controllers/commercialProposalController.js";
import { attachPhoto as attachDailyReportPhoto, create as createDailyReport, finalize as finalizeDailyReport, generate as generateDailyReport, get as getDailyReport, list as listDailyReports, photoUpload as dailyReportPhotoUpload, removePhoto as removeDailyReportPhoto, update as updateDailyReport } from "../controllers/dailyReportController.js";

const router=express.Router();
router.use(requireAuth,allowRoles(1));
router.get("/",listWorkflows);
router.get("/:requestId",getWorkflow);
router.post("/:requestId/initialize",initializeWorkflow);
router.patch("/:requestId/stage",updateWorkflowStage);
router.patch("/:requestId/quotation",selectQuotation);
router.post("/:requestId/confirm",confirmQuotation);
router.post("/:requestId/proposal/draft",saveDraft);
router.post("/:requestId/proposal/send",sendProposal);
router.post("/:requestId/proposal/supersede",recallProposal);
router.put("/:requestId/preparation",savePreparation);
router.post("/:requestId/preparation/complete",completePreparation);
router.get("/:requestId/templates",getTemplates);
router.post("/:requestId/checklist/template",selectTemplate);
router.put("/:requestId/checklist",saveChecklist);
router.post("/:requestId/checklist/complete",completeChecklist);
router.get("/:requestId/daily-reports",listDailyReports);
router.post("/:requestId/daily-reports",createDailyReport);
router.get("/:requestId/daily-reports/:dailyReportId",getDailyReport);
router.put("/:requestId/daily-reports/:dailyReportId",updateDailyReport);
router.post("/:requestId/daily-reports/:dailyReportId/generate",generateDailyReport);
router.post("/:requestId/daily-reports/:dailyReportId/finalize",finalizeDailyReport);
router.post("/:requestId/daily-reports/:dailyReportId/photos/upload-url",dailyReportPhotoUpload);
router.post("/:requestId/daily-reports/:dailyReportId/photos",attachDailyReportPhoto);
router.delete("/:requestId/daily-reports/:dailyReportId/photos/:photoId",removeDailyReportPhoto);
router.post("/:requestId/evidence/upload-url",evidenceUpload);
router.post("/:requestId/evidence",attachEvidence);
router.delete("/:requestId/evidence/:evidenceId",removeEvidence);
router.post("/:requestId/report/generate",generateDraft);
router.post("/:requestId/report/review",reviewReport);
router.post("/:requestId/report/confirm",confirmReport);
router.post("/:requestId/complete",markInspectionComplete);
router.post("/:requestId/invoice/upload-url",invoiceUpload);
router.post("/:requestId/invoice",createInvoice);
router.post("/:requestId/invoice/approve",approveWorkflowInvoice);
router.post("/:requestId/invoice/reject",rejectWorkflowInvoice);
router.post("/:requestId/invoice/pay",payWorkflowInvoice);
export default router;
